### ISSUE TITLE
Instalação e utilização

### ISSUE THREAD

**Issue by DaniJCV** [One-Shift/BO2-BOxygen#30]
Boa tarde,

Considerando que o BO3 ainda náo está disponível na sua totalidade, tentei agora instalar o BO2. Correu tudo bem até que o sistema após o login me encaminha para umas páginas /0 só que nada existe. 

No demo elas existem (é o Backoofice em si), onde as posso obter?

**Comment by MarcosSilvaAv** [comment]
Boa noite DaniJCV,

no ficheiro backoffice/configuration.php, como tens as seguintes opções 

```
"path" => ""
"path-bo" => ""
```

Cumprimentos,
Marcos Silva

**Comment by DaniJCV** [comment]
Ambas estao preenchidas com os dados corretos no entanto o sistema encaminha-me para o que será o bo/0 em todas as páginas

**Comment by MarcosSilvaAv** [comment]
Mais uma pergunta, o .htaccess encontra-se presente.

Comprimentos,
Marcos Silva

**Comment by MarcosSilvaAv** [comment]
Uma pergunta diferente, instalaste o bo2 na raiz? Ou tens dentro de uma pasta?

Cumprimentos,
Marcos Silva

**Comment by DaniJCV** [comment]
Está na raiz :)

**Comment by DaniJCV** [comment]
Acrescento que estou a usar a versão 1.2, (que descarreguri o zip aqui no GitHub) estará relacionado com isso?

**Comment by MarcosSilvaAv** [comment]
Então tens os path em branco certo?

```
"path" => ""
"path-bo" => ""
```
Assim?

Porque o Bo2-BOxygen é usado em conjunto com o BO2-website-base.

Deixo aqui uns vídeos tutorial, https://m.youtube.com/playlist?list=PL9JU6Qe5rdxH1tht5Eb6CoO5SQ0m8ylfb

**Comment by DaniJCV** [comment]
Tenho sim. 

Até "reconfigurei" assim,  Usando o BO2-Oxigen com o BO2-website-base
```
> "path" => ""
> "path-bo" => "/backoffice"
```

E após login (dados demo) e surgir a mensagem " Your session has been initiated!" sou encaminhado para dominio/backoffice/0

**Comment by c42759** [comment]
@DaniJCV Pelo que estou a ver presumo que estejas a usar um servidor local como por exemplo "LAMP" ou "XAMP".

As configurações estão corretas, se o projeto se encontrar na raiz do public_html ou htdocs (dependendo do serviço de apache).
Caso estejas com o projeto por exemplo em http://localhost/projeto-1/ as configurações deverão ser as seguintes:

```
> "path" => "/projeto-1"
> "path-bo" => "/projeto-1/backoffice"
```

Espero ter ajudado,

**Comment by DaniJCV** [comment]
Neste caso estou num domínio que posso deixar aqui.

http.//expheron.xyz e o backoffice em http.//expheron.xyz/backoffice


Ao fazer login com dados (iguais ao vosso demo) e depois de login é que sou diretamente encaminhado para http.//expheron.xyz/backoffice/0


Mais uma vez digo que descarreguei o zip (através do sistema do GitHub) da versão que está carregada (1.2.0) e faz-me isso. Ao descarregar a 1.1.0 através do link da descrição está normal.


Grato por toda a ajuda!

Cumprimentos

**Comment by c42759** [comment]
@DaniJCV procedi ao teste de login no endereço que indicas-te. Pelo erro que é apresentado, poderá ser por 2 motivos.

1) o ficheiro .htaccess presente na pasta /backoffice não foi carregado ou se foi poderá estar danificado.
2) Se foi carregado com sucesso, o servidor onde se encontra alocado, pode não permitir alguma das configurações que são feitas pelo prórpio .htaccess

**Comment by DaniJCV** [comment]
Vou testar noutro servidor e mais tarde deixo feedback :) Grato pela ajuda!

**Comment by DaniJCV** [comment]
Estou a ter error 500 após uma instalação diferente. Após login o index.php tenho esse erro.

**Comment by c42759** [comment]
@DaniJCV encontras-te a usar a versão 3.3.0RC?

**Comment by DaniJCV** [comment]
@c42759 a usar a mais recente disponível para download

v1.2.0r6.zip nota que é o BO2. O BO3 também tenho o mesmo problema (V. v3.3.0 RC)

**Comment by DaniJCV** [comment]
![image](https://user-images.githubusercontent.com/8714143/43213063-84a6a74e-902d-11e8-8e16-c29f6b39a527.png)
Mas é normal as páginas ficarem em branco?

**Comment by c42759** [comment]
@DaniJCV verifiquei que existia um erro num dos ficheiros de login.

Pedia que efetuasses a atualização do seguinte ficheiro: https://github.com/One-Shift/BO3-BOzon/blob/master/backoffice/modules/sys-login/actions/home.php

**Comment by c42759** [comment]
@DaniJCV podes sempre juntar-te ao nosso grupo no telegram para uma ajuda mais rápida e em live.

Link: https://t.me/joinchat/BKjv1BHwHQvK6_oh1CyEfg
